### ISSUE TITLE
Add layer name instead of/in addition to the layer number

### ISSUE THREAD

**Issue by joeribekker** [GemeenteUtrecht/beheerconsole#8]
Current situation:

*  Layer 1
*  Layer 2
*  Layer 3
*  ...
*  

I'm fairly into Common Ground but I still mess up the layer ordering. Can we just add meaningful names everywhere (labels, filters, etc.):

* 5, Applicaties
* 4, Processen
* 3, Integratie
* 2, API's
* 1, Opslag

**Comment by sergei-maertens** [comment]
Fixed in d8bd3b7f01aa9353f44793c7c92f94e0be0f7761
